apiVersion: v1
kind: Pod
metadata:
  name: gop-file-server
  labels:
    run: jekyl
spec:
  containers:
  -  name: gop-file-server
     image: kodekloud/fileserver
     volumeMounts:
        - name: data-store
          mountPath: /web
  
  volumes:
    - name: data-store
      persistentVolumeClaim:
        claimName: data-pvc
