---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: martin
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
