apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "persistentvolumeclaims", "pods"]
    verbs: [" * "]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: martin
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
