apiVersion: v1
kind: Service
metadata:
  labels:
    run: jekyl
  namespace: development
  name: jekyll
spec:
  ports:
    - port: 8080
      targetPort: 4000
      nodePort: 30097
  selector:
    run: jekyl
  type: NodePort
