apiVersion: apps/v1
kind: Deployment
metadata:
  
  labels:
    app: redis-deployment
  name: redis-deployment
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  strategy: {}
  template:
    metadata:
    
      labels:
        app: redis-deployment
    spec:
      containers:
      - image: redis:alpine
        name: redis
        volumeMounts:
        -  name: redis-data
            mountPath: /data
      volumes: 
      -  name: redis-data
          emptyDir: {}  
