apiVersion: v1
kind: Service
metadata:
 
  labels:
    app: redis-deployment
  name: redis
  namespace: vote
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-deployment
  type: ClusterIP
status:
  loadBalancer: {}